security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        default:
            entity: { class: Tracko\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
          pattern:  ^/.*
          provider: default
          form_login:
              check_path: /do_login
              login_path: /user/login
              use_forward: false
              default_target_path: /
              always_use_default_target_path: false
          logout:
              path:   /logout
              target: /
          anonymous: ~
          switch_user: { parameter: _impersonate_user }
          remember_me:
            key: %secret%
            lifetime: 3600
            path: /
            domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: /secured/, roles: ROLE_USER }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
