parameters:
#    tracko_base.example.class: Tracko\BaseBundle\Example

services:
#    tracko_base.example:
#        class: %tracko_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
